version: '3.8'

services:
  zabbix_service:
    build: 
      context: ./services/zabbix_service
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    volumes:
      - ./services/zabbix_service:/app
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=development
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:5003/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  map_service:
    build: 
      context: ./services/map_service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./services/map_service:/app
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=development
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  analysis_service:
    build: 
      context: ./services/analysis_service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    volumes:
      - ./services/analysis_service:/app
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=development
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  access_point_service:
    build: 
      context: ./services/access_point_service
      dockerfile: Dockerfile
    ports:
      - "5004:5004"
    volumes:
      - ./services/access_point_service:/app
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=development
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5004/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - app-network

  frontend_service:
    build: 
      context: ./services/frontend_service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./services/frontend_service:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - PYTHONPATH=/app
    depends_on:
      gateway:
        condition: service_healthy
    networks:
      - app-network

  gateway:
    build: 
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./gateway:/app
    environment:
      - FLASK_APP=app.main
      - FLASK_ENV=development
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      zabbix_service:
        condition: service_healthy
      map_service:
        condition: service_healthy
      analysis_service:
        condition: service_healthy
      access_point_service:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16